### ISSUE TITLE
Path.exists is not patched

### ISSUE THREAD

**Issue by sassanh** [pytest-dev/pyfakefs#1021]
**Describe the bug**
I call `Path().exists` immediately after `shutil.copyfile` and it returns `False` while `os.path.exists` returns `True`.
I guess `Path().exists` is using the real filesystem.

**How To Reproduce**
```python
Path('/tmp/test').write_text('test')
print(Path('/tmp/test').exists())
print(os.path.exists('/tmp/test'))
```

**Your environment**
```
macOS-14.5-arm64-arm-64bit
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
pyfakefs 5.5.0
pytest 8.2.1
```

**Comment by sassanh** [comment]
I also noticed `Path().unlink` doesn't work (maybe it is working on the real filesystem) while `os.remove` works.

**Comment by mrbean-bremen** [comment]
Can you please show how you call that code? E.g. a reproducible example, if possible.

**Comment by mrbean-bremen** [comment]
For illustration - the following test passes:
```py
def test_fakefs(fs):
    fs.os = OSType.LINUX
    path = Path('/tmp/test')
    path.parent.mkdir(exist_ok=True)
    path.touch()
    path.write_text('test')
    assert path.exists()
    assert os.path.exists('/tmp/test')
```
So you must be doing something different.

**Comment by sassanh** [comment]
Thanks for investigating it! I probably did something wrong, I will check it when I get back to my desk.

**Comment by sassanh** [comment]
It was an issue on my side, I had `pathlib` in `additional_skip_names` from the past 🙈
I will make sure to create simple reproduction steps before reporting any issues in the future.

**Comment by sassanh** [comment]
@mrbean-bremen Quick question, is `Path().exists` expected to respect `additional_skip_names`?

**Comment by mrbean-bremen** [comment]
Well... I had hoped you won't ask :)

The truth is that I did want to implement a more generic solution for the handling of `additional_skip_names` in `pathlib`, but couldn't get it to work. The current implementation is incomplete (yes, actually all methods should respect `additional_skip_names`) and ugly (using the callstack). I had hoped that it will sufficient until I get back to it, but obviously I was wrong.

Feel free to write a new issue. Maybe you even have an idea on how to implement this in a better way...
