### ISSUE TITLE
please make applying the umask configurable for create_dir()

### ISSUE THREAD

**Issue by jcfp** [pytest-dev/pyfakefs#1038]
Recent changes made pyfakefs apply the umask by default when creating files or dirs. For `create_file()`, this behaviour is configurable via the `apply_umask` parameter. Please add a similar parameter for `create_dir()`, to allow for ignoring the umask and thus enabling full control of the exact permissions on the new dir via the `perm_bits` parameter.

Currently, we work around the umask always getting applied to directories by configuring an unrealistic all-permissive umask ("0000") on the fake filesystem ([like so](https://github.com/sabnzbd/sabnzbd/blob/f50810fb58656d9a3c33befb601ed63c1be105cf/tests/test_filesystem.py#L952)) to get rid of some test failures (https://github.com/sabnzbd/sabnzbd/issues/2883). Having an option to control the behaviour of `create_dir()` would obviously be a lot nicer.

**Comment by mrbean-bremen** [comment]
Sure, that makes sense - I hadn't thought about this at the time.

**Comment by mrbean-bremen** [comment]
I guess you will need a release with the change?

**Comment by mrbean-bremen** [comment]
A [new release](https://pypi.org/project/pyfakefs/5.6.0/) is out.

**Comment by Safihre** [comment]
Thanks @mrbean-bremen !
