### ISSUE TITLE
Question: mounting Git in fake filesystem

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pyfakefs#1056]
Is it possible to mount Git inside a fake filesystem? 😄 

```python
import os
import pathlib

from pre_commit.main import main

REPO_ROOT = pathlib.Path(__file__).parent.parent

def test_something(fs) -> None:
    fs.add_real_directory(REPO_ROOT, read_only=False)
    os.chdir(REPO_ROOT)
    main(("run", "--all-files"))
```

Running the above code with `pre-commit==3.8.0`, `pytest==8.3.2`, and `pyfakefs==5.6.0`, I am getting:

```none
        try:
            root = os.path.abspath(
                cmd_output('git', 'rev-parse', '--show-cdup')[1].strip(),
            )
            inside_git_dir = cmd_output(
                'git', 'rev-parse', '--is-inside-git-dir',
            )[1].strip()
        except CalledProcessError:
>           raise FatalError(
                'git failed. Is it installed, and are you in a Git repository '
                'directory?',
            )
E           pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

Given that `pyfakefs` doesn't work with `subprocess.run` (https://github.com/pytest-dev/pyfakefs/issues/447), I am wondering how to run something like `git init` inside a fake filesystem.

**Comment by mrbean-bremen** [comment]
I'm afraid this is outside of the capabilities  of `pyfakefs`. The main limitation in `pyfakefs` is that it can only patch Python filesystem calls, not C filesystem calls, so I don't see a way to make this work.

**Comment by jamesbraza** [comment]
Alright sounds good, thanks for answering. I am going to close this out as resolved, thanks again!
