### ISSUE TITLE
`ResourceWarning` on Python 3.13

### ISSUE THREAD

**Issue by kurtmckee** [pytest-dev/pyfakefs#1059]
**Describe the bug**

When an unclosed file is garbage collected, CPython automatically raises a `ResourceWarning`. However, this is ignored by default unless warnings are escalated to errors.

I escalate warnings to errors in my projects' test suites to help ensure I'm closing open resources throughout the codebase, and discovered that pyfakefs on Python 3.13 opens a file but doesn't close it, which triggers a `ResourceWarning`.

**How To Reproduce**

I've tried for hours to trigger this warning in the pytest codebase, but have been unsuccessful so far. Therefore I've created a self-contained repo that demonstrates the issue:

https://github.com/kurtmckee/demo-pyfakefs-py3.13-resource-warning

For posterity, this is the Python code in a `test_demo.py` file:

```python
def test_resource_warning(fs):
    pass
```

and this is all that's needed to cause the `ResourceWarning` and get a traceback showing where the object was instantiated:

```console
$ PYTHONTRACEMALLOC=30 python3.13 -m pytest -Wall
```

**Your environment**

```
Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python 3.13.0rc2 (main, Sep  9 2024, 11:30:52) [GCC 11.4.0]
pyfakefs 5.6.0
pytest 8.3.2
```

**Comment by kurtmckee** [comment]
Well! I finally opened the actual pyfakefs repo to fix the bug and discovered that it's already fixed by 4d68c0f239cf77e04a3ec390f5eb9735fe8a35b2, which removed `_real_call_line_no`, which was the source of the issue.

If you have an opportunity (and feel HEAD is in a good state), would you consider release a new version of pyfakefs? It'll help me resolve CI errors in a number of my projects.

Thanks for your time and consideration!

**Comment by mrbean-bremen** [comment]
Yes , `_real_call_line_no` was a temporary workaround, until I found a better fix. I'm still not completely happy with the the 3.13 state due to the need to reload `glob`, which impacts the test performance. Maybe I can find another way to fix that problem before the 3.13 release.

I had planned to make a release with "official" 3.13 support as soon as it is released (planned for 1st of October), but I can make one earlier. I still want to wait for feedback for the PR that is currently in the work, and maybe merge it before that, so it may still take a few days.

**Comment by mrbean-bremen** [comment]
Sorry for the long delay, I just wanted to make one change before the release (remove that reloading of `glob`, that hit the test performance), but couldn't get to it. I did it only today, and I think I will now do the release with the official release of Python 3.13, which should be October 1st.

**Comment by kurtmckee** [comment]
Thank you so much for working on this, and for your work on pyfakefs! It's extremely helpful for my testing workflows! ❤️

**Comment by mrbean-bremen** [comment]
Thanks! 😀

**Comment by mrbean-bremen** [comment]
FYI: the release is finally out (together with the Python 3.13 release yesterday).

**Comment by kurtmckee** [comment]
Nice! Thank you!
