### ISSUE TITLE
`pdb` does not load .pdbrc configuration file when invoke via `breakpoint()`

### ISSUE THREAD

**Issue by JD-Veiga** [pytest-dev/pyfakefs#731]
**Describe the bug**

Not really a bug, just for the record. I think I have found another example of "**The test code tries to access files in the real filesystem**": it is `pdb` module when invoke via `breakpoint()` built-in function.

When a `breakpoint()` is placed in a section of code where file system is mocked by `pyfakefs`, `pdb` cannot access the real file ".pdbrc". This file can be used for configuring the behaviour of `pdb`, specially, by defining new commands via `alias`.

`breakpoint()` invokes `pdb` module which read a ".pdbrc" file using `open()` built-in function. Of course, if this function was been patched by `pyfakefs`, ".pdbrc" will not be found --unless access to real file was granted. 

**How To Reproduce**

I have written two files to check this behaviour:  .pdbrc and testing_pdbrc.py.

The local .pdbrc file is:

```
alias hello print('Hello, .pdbrc has been loaded')
```

which simply prints a hello message when `hello` command is typed in the `pdb` interpreter.

The Python script called `testing_pdbrc.py` consists in:

```
import unittest
import pathlib

from pyfakefs import fake_filesystem_unittest


def show(something):
    print()
    print(something)
    print()
    breakpoint()


class FakeFsTestCase(fake_filesystem_unittest.TestCase):

    def setUp(self) -> None:
        self.setUpPyfakefs()

    def test_show(self):
        show(pathlib.Path)


class RealFsTestCase(unittest.TestCase):

    def test_show(self):
        show(pathlib.Path)

```

Both files must be in the same directory and must be invoked from that directory.

When running `python -m unittest testing_pdbrc`, you get something like:

```

<class 'pyfakefs.fake_pathlib.FakePath'>

--Return--
> [...]/testing_pdbrc/testing_pdbrc.py(11)show()->None
-> breakpoint()
(Pdb) hello
*** NameError: name 'hello' is not defined
(Pdb) c
.
<class 'pathlib.Path'>

--Return--
> [...]/testing_pdbrc/testing_pdbrc.py(11)show()->None
-> breakpoint()
(Pdb) hello
Hello, .pdbrc has been loaded
(Pdb) c
.
----------------------------------------------------------------------
Ran 2 tests in 9.453s

OK
```

which basically means that .pdbrc is loaded when the script is working on the real file system but not when it is working on the fake file system provided by `pyfakefs`.

Note that `breakpoint()` always tries to open .pdbrc, even if it has been previously loaded.

As I have previously noted, this is not really a bug. I have just mentioned it for the record. This behaviour can confused people using `pdb` --though I think that `pdb` is not quite popular as other debugger and few people will take advantage of .pdbrc in real world.

**Your environment**

macOS-10.14.6-x86_64-i386-64bit
Python 3.10.7 (main, Sep 10 2022, 07:38:13) [Clang 10.0.1 (clang-1001.0.46.4)]
pyfakefs 5.0.0

Thank you.

**Comment by mrbean-bremen** [comment]
Thanks - I may have a look at this some time later. I don't know what part of pdb accesses the config file, but it must be a Python module (otherwise it would not be patched), and maybe it can be excluded using [additional_skip_names](https://pytest-pyfakefs.readthedocs.io/en/latest/usage.html#additional-skip-names) or `fake_filesystem_unittest.Patcher.SKIPNAMES`.

**Comment by JD-Veiga** [comment]
Using `self.setUpPyfakefs(additional_skip_names=['pdb'])` works.

Thank you.

**Comment by mrbean-bremen** [comment]
Good to hear - can we close this, then?

**Comment by JD-Veiga** [comment]
Just a final thought: since `pdb` is invoked by a built-in function `breakpoint()` and it is used in a temporal basis (just debugging a piece of code while developing) instead of being mocked for running tests, should not be permanently skipped? 

I feel awkward to need remember adding `additional_skip_names=['pdb']` to each test suite just in case I decide to debug it in the future.

I have tested to add pdb to `SKIPNAMES: Set[str] = {'pdb'}` in `fake_filesystem_unittest.py` and it works (and passes tests). Of course, I do not know if it is a good solution or if it would have any further impact in other parts of the package.

Thank for help.

**Comment by mrbean-bremen** [comment]
You can add it to the global `SKIPNAMES` somewhere in your initialization code, or can use your own derived TestCase instance which always adds this to `additional_skip_names` (or, if you are using `pytest`, use your own fixture that does that). 
It is unlikely to cause side effects, but we don't want to add this as a default, as it is seldom needed (other debuggers may need another configuration), and the more defaults we add, the higher the probability of side effects in some scenarios.
