### ISSUE TITLE
Next release before 23th January (Debian freeze)

### ISSUE THREAD

**Issue by buhtz** [pytest-dev/pyfakefs#759]
Please prepare a new release (minimum two weeks) before the 23th January.
At this date Debian will do enter its freeze phase.

Give the distro maintainers some time to prepare your package.

Please let me know if you don't have direct contact to them to trigger a new package process. I can do the contact in that case.

**Comment by mrbean-bremen** [comment]
Thanks for the reminder! I tend to make patch releases frequently enough, so this should not be problem. Probably some time around Christmas...

I don't have direct contact to package maintainers, only occassionally if there is a problem wth packacking a version.

**Comment by mrbean-bremen** [comment]
Release done.

**Comment by buhtz** [comment]
Great. Usually Debian automatically track new upstream released.
But to speed the process up I opened a wishlist-bug on Debian
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028582
