### ISSUE TITLE
test_write_to_read_fd fails on OpenIndiana/illumos

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/pyfakefs#768]
**Describe the bug**

I'm packaging `pyfakefs` for [OpenIndiana](https://www.openindiana.org/) (illumos based distro) and I noticed that during pytest run the `test_write_to_read_fd` test fails.  The problem is that `test_write_to_read_fd` expects `pipe()` to open one file as read-only and the other one as write-only.  This is apparently true for Linux, but not for illumos where the `pipe()` is implemented differently and both files are opened for read and write: https://illumos.org/man/2/pipe.  Also, POSIX leaves this explicitly unspecified: https://pubs.opengroup.org/onlinepubs/9699919799/functions/pipe.html so `test_write_to_read_fd` should not rely on it.

**How To Reproduce**
```
/usr/bin/python -m pytest --color=no --verbose
```
```
____________________ FakeOsModuleTest.test_write_to_read_fd ____________________

self = <pyfakefs.tests.fake_os_test.FakeOsModuleTest testMethod=test_write_to_read_fd>

    def test_write_to_read_fd(self):
        read_fd, write_fd = self.os.pipe()
>       self.assert_raises_os_error(errno.EBADF,
                                    self.os.write, read_fd, b'test')

pyfakefs/tests/fake_os_test.py:2793:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyfakefs/tests/test_utils.py:404: in assert_raises_os_error
    self.fail('No exception was raised, OSError expected')
E   AssertionError: No exception was raised, OSError expected
```

**Your environment**
```bash
$ python -c "import platform; print(platform.platform())"
SunOS-5.11-i86pc-i386-64bit-ELF
$ python -c "import sys; print('Python', sys.version)"
Python 3.9.16 (main, Dec 22 2022, 11:59:25) 
[GCC 10.4.0]
$ python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
pyfakefs 5.0.0
$ python -c "import pytest; print('pytest', pytest.__version__)"
pytest 7.2.0
$
```

**Comment by mrbean-bremen** [comment]
Thanks - good point. Pyfakefs is explicitely only supported for Linux, macOS and Windows and only tested there, so this kind of problems will not surface in the tests. I'll probably just remove that test, or better add a system check.
When would you need a patch release? I could do one over the weekend, or wait a bit more to see if anything else comes up.

**Comment by mtelka** [comment]
I do not need new release to get this issue fixed.  I simply [skipped the test using `pytest.mark.skip`](https://github.com/OpenIndiana/oi-userland/pull/10387) and everything is okay here now.  So no need to hurry.  Thank you.
