### ISSUE TITLE
Python 3.12 beta1: no attribute 'parse_parts'

### ISSUE THREAD

**Issue by buhtz** [pytest-dev/pyfakefs#830]
### Description
Yesterday the first Beta of Python 3.12 was released. So I triggered the TravisCI build and my testsuite with that Python version in my own project [_Back In Time_](https://github.com/bit-team/backintime).

There might be a problem with `pyfakefs` and Python 3.12 (`--version` on TravisCI returns `Python 3.12.0a2+`). But I'm not sure.

The error message from the test run is

```
======================================================================
ERROR: test_git_repo_info (test.test_diagnostics.Diagnostics_FakeFS.test_git_repo_info)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/buhtz/backintime/common/test/test_diagnostics.py", line 108, in test_git_repo_info
    self.assertEqual(diagnostics.get_git_repository_info(), None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/travis/build/buhtz/backintime/common/diagnostics.py", line 278, in get_git_repository_info
    git_folder = path / '.git'
                 ~~~~~^~~~~~~~
  File "/opt/python/3.12-dev/lib/python3.12/pathlib.py", line 709, in _
```_truediv__
    return self._make_child((key,))
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.12-dev/lib/python3.12/pathlib.py", line 455, in _make_child
    drv, root, parts = self._parse_args(args)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.12-dev/lib/python3.12/pathlib.py", line 426, in _parse_args
    return cls._flavour.parse_parts(parts)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/travis/virtualenv/python3.12-dev/lib/python3.12/site-packages/pyfakefs/fake_path.py", line 481, in __getattr__
    return getattr(self._os_path, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'parse_parts'

```

### Reproduce

The code of the test can be found here.

https://github.com/buhtz/backintime/blob/1cb873c06305426dfb401353540a50149277c2c8/common/test/test_diagnostics.py#L103-L134

I'm not able to run Python 3.12 locally on my machine. So I'm not able to create an MWE. But I'll try to figuring out to do this with a Python3.12-docker-thing.

### Research

Python 3.11 has [`pathlib._Flavour.parse_parts()`](https://github.com/python/cpython/blob/76873ca6b1ad1a1eb9518f0ff7fc594ec96d0a65/Lib/pathlib.py#L56). But it is gone in Python 3.12; including the `class _Flavour`.

I checked the commit and PR history and found nothing but I'm also not good in handling such git features.

I also can not see something relevant in the [CHANGELOG](https://docs.python.org/3.13/whatsnew/3.12.html#pathlib).

I asked the CPython people: https://github.com/python/cpython/issues/104921 and they gave detailed answers that might help you with fixing this.

**Comment by mrbean-bremen** [comment]
Please check with the main branch and reopen if the issue is still there. Note that the code is no longer compatible with the latest alpha.

**Comment by buhtz** [comment]
I can confirm you are right.

After TravisCI no supports `Python 3.12.0b1+` there is no error anymore.
