### ISSUE TITLE
Docs: using `pytest.mark.usefixtures` in code snippets

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pyfakefs#834]
**Is your feature request related to a problem? Please describe.**

 

Many of the `pytest`-oriented examples in https://pytest-pyfakefs.readthedocs.io/en/stable/usage.html use a `fake_fs` fixture in the test signature, but don't actually use it in the test body.

Here's a more specific example: https://pytest-pyfakefs.readthedocs.io/en/stable/usage.html#access-to-files-in-the-real-file-system

```python
def test_using_fixture1(my_fs):  # Linters don't like this line
    with open(os.path.join(fixture_path, "fixture1.txt")) as f:
        contents = f.read()
```

Multiple linters detect this line as unused code:
- `pylint`: `invalid-name` gets emitted on test functions or methods
- `flake8-unused-arguments`: `ARG001` gets emitted if test function, or `ARG002` gets emitted if test method

**Describe the solution you'd like**

This can be ameliorated with using `pytest.mark.usefixtures` decorator:

```python
@pytest.mark.usefixtures("my_fs")
def test_using_fixture1():
    with open(os.path.join(fixture_path, "fixture1.txt")) as f:
        contents = f.read()
```

Can we move code snippets in the `pyfakefs` docs to use `pytest.mark.usefixtures`?

**Comment by mrbean-bremen** [comment]
Thanks, this would make sense, probably with a line explaining it. 
If you want to make a PR, go ahead - otherwise this gets at the end of my personal backlog 😀
