### ISSUE TITLE
On `patch_open_code`

### ISSUE THREAD

**Issue by alexei** [pytest-dev/pyfakefs#876]
The [documentation on `patch_open_code`](https://pytest-pyfakefs.readthedocs.io/en/latest/usage.html#patch-open-code) has a note saying:

> This argument is subject to change or removal in future versions of pyfakefs, depending on the upcoming use cases.

I feel a little bit lost in translation here and I'm not sure what the note means. Is it a deprecation warning? Is it something else? I'd appreciate it if you reworded it or, anyway, clarified your intentions about the argument.

My program has functions that import Python modules dynamically (via `importlib`). I use `patch_open_code` to test those parts. I need to know whether it's safe to use this option. If, however, there are plans to drop it, then I will consider using the real fs.

**Comment by mrbean-bremen** [comment]
There are no plans to drop this, if it is used. As for "subject for change" - it wasn't clear if the current behavior is sufficient or even useful, but at this point there are no plans to change it.
I can just remove this part of the documentation. It was only there as long as the feature was considered experimental, which it isn't now.

**Comment by alexei** [comment]
Thank you for the positive response!
