### ISSUE TITLE
`patch_open_code` doesn't seem to work in Python 3.12

### ISSUE THREAD

**Issue by alexei** [pytest-dev/pyfakefs#892]
I have a program that imports Python modules dynamically and I use `patch_open_code` in my tests. I tried running it under Python 3.12 just for fun and found the tests are not working.

For example, this works in e.g. 3.11:

```python
import importlib.util
from contextlib import redirect_stdout
from io import StringIO

import pytest
from pyfakefs.fake_filesystem_unittest import Patcher, PatchMode


@pytest.fixture
def fffs():
    with Patcher(patch_open_code=PatchMode.AUTO) as patcher:
        yield patcher.fs


def import_foo():
    spec = importlib.util.spec_from_file_location("bar", "/foo/bar.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)


def test_foo(fffs):
    fffs.create_file("/foo/bar.py", contents="print('hello')")
    with redirect_stdout(StringIO()) as stdout:
        import_foo()
    assert stdout.getvalue() == "hello\n"
```

The test passes alright. In 3.12, however, I'm getting:

```
__________________________________ test_foo ___________________________________

fffs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0xBAADF00D>

    def test_foo(fffs):
        fffs.create_file("/foo/bar.py", contents="print('hello')")
        with redirect_stdout(StringIO()) as stdout:
>           import_foo()

/test_ffs.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/test_ffs.py:18: in import_foo
    spec.loader.exec_module(mod)
<frozen importlib._bootstrap_external>:990: in exec_module
    ???
<frozen importlib._bootstrap_external>:1127: in get_code
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_frozen_importlib_external.SourceFileLoader object at 0xDEADC0DE>, path = '/foo/bar.py'

>   ???
E   FileNotFoundError: [Errno 2] No such file or directory: '/foo/bar.py'

<frozen importlib._bootstrap_external>:1185: FileNotFoundError
```

Tested under Python 3.11.6 and 3.12.0, respectively, with pytest 7.4.0 and pyfakefs 5.2.4.

**Comment by mrbean-bremen** [comment]
Thanks, I will have a look at it. It may be related to #836, which I hadn't yet managed to fix yet. Now that 3.12 is released, this gets a bit more important...

**Comment by alexei** [comment]
Let me know what I can do to help. For example, it doesn't look like this use case (i.e. importing modules) is covered with tests. I could open a PR to add the above code to `pyfakefs`. What are your thoughts on this?

**Comment by mrbean-bremen** [comment]
Thanks - I can basically just use your code as a test, and I can reproduce the problem. 
I think I already found a trivial fix, that hopefully also fixes the other problem.

**Comment by mrbean-bremen** [comment]
I couldn't get it to work under Windows yet (only in the CI, locally in works), but it helped me to fix the other problem with patching `open` (this was indeed a trivial fix).
For some reason, your test works under Windows only with Python 3.9, not with 3.8 and 3.10-3.12. I suppose that it didn't work before either, at least in the CI (still have no idea what is different from my local setup). I will have another go some time later this week...

**Comment by mrbean-bremen** [comment]
Should be fixed in main now - please check!

**Comment by mrbean-bremen** [comment]
New version with the fix is released.

**Comment by alexei** [comment]
@mrbean-bremen thanks for looking into this. I can confirm it's working 👍
