### ISSUE TITLE
Fake filesystem is paused after yielding in a fixture

### ISSUE THREAD

**Issue by AliShazly** [pytest-dev/pyfakefs#913]
**Describe the bug**
After returning back to a fixture that yielded, the fake filesystem seems to be paused. The expected behavior would be for the fake filesystem to stay active until the fixture returns.
This only started happening in v5.3.1, it behaves as expected in v5.3.0. From a cursory look, it seems like the breaking change happened in 73fb5d2.

**How To Reproduce**
This test errors because the fake filesystem isn't active after yielding, making it so that `os.rmdir` searches the real filesystem for the test directory to delete. Calling `fs.resume()` after `yield` fixes the error.
```py
import os
import pytest


@pytest.fixture(autouse=True)
def setup_teardown(fs):
    dirname = "test_directory"
    os.mkdir(dirname)
    yield
    # fs.resume()  # Uncomment this line and the test passes.
    os.rmdir(dirname)


def test_pass():
    pass
```

Here's the test output:
```
============================================ test session starts ============================================
platform win32 -- Python 3.10.2, pytest-7.4.3, pluggy-1.3.0
rootdir: C:\Users\ali\dev\fakefstest
plugins: pyfakefs-5.3.1
collected 1 item

repro.py .E                                                                                            [100%]

================================================== ERRORS ===================================================
______________________________________ ERROR at teardown of test_pass _______________________________________

fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x0000022A04CE6FB0>

    @pytest.fixture(autouse=True)
    def setup_teardown(fs):
        dirname = "test_directory"
        os.mkdir(dirname)
        yield
        # fs.resume()  # Uncomment this line and the test passes.
>       os.rmdir(dirname)
E       FileNotFoundError: [WinError 2] The system cannot find the file specified: 'test_directory'

repro.py:11: FileNotFoundError
========================================== short test summary info ==========================================
ERROR repro.py::test_pass - FileNotFoundError: [WinError 2] The system cannot find the file specified: 'test_directory'
======================================== 1 passed, 1 error in 0.11s =========================================
```

**Your environment**
```
Windows-10-10.0.19045-SP0
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
pyfakefs 5.3.1
pytest 7.4.3
```

Thanks!

**Comment by mrbean-bremen** [comment]
Thanks for the report!
This is expected behavior - after yield the fake filesystem is shut down and should not be accessed. It may be paused and not yet shut down at that point, but that is an implementation detail and should not be relevant to the user.
It also makes no sense to delete files in the fake filesystem after or during filesystem shutdown, as the files (which live only in the RAM) will be gone anyway after shutdown.

**Comment by AliShazly** [comment]
Ah, gotcha. Thanks for taking a look at this

**Comment by mrbean-bremen** [comment]
You are welcome!
