### ISSUE TITLE
sdist is missing `tox.ini`

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/pyfakefs#937]
The sdist package at PyPI is missing `tox.ini`.  Please add the missing file to sdist to make downstream testing easier.  Thank you.

**Comment by mrbean-bremen** [comment]
Sure, that makes sense.

**Comment by mrbean-bremen** [comment]
Shall be in the release. There will probably another patch release soon due to a regression.

**Comment by mrbean-bremen** [comment]
Fix with release 5.3.5.
