### ISSUE TITLE
Example usage docs using pathlib leads to errors

### ISSUE THREAD

**Issue by lsfischer** [pytest-dev/pyfakefs#946]
**Describe the bug**
Spotted by @jczulian, following the [example usage docs](https://pytest-pyfakefs.readthedocs.io/en/latest/usage.html#patch-using-fake-filesystem-unittest), specifically the example using `pathlib.Path`, the example test case results in a failed test run with `FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/test'`.

From what I can gather, this seems to be because internally it will hit [this line](https://github.com/pytest-dev/pyfakefs/blob/56e59110382d5cb446a5c293b9ea7b92f83999a5/pyfakefs/fake_open.py#L298-L300) where `create_missing_dirs=False`, thus the `test` parent directory is not created.

**How To Reproduce**
The example unit test from [the docs ](https://pytest-pyfakefs.readthedocs.io/en/latest/usage.html#patch-using-fake-filesystem-unittest) can be used to reproduce the issue
(Also note that `import os` is missing)
```python
from pyfakefs.fake_filesystem_unittest import TestCase
import os

class ExampleTestCase(TestCase):
    @classmethod
    def setUpClass(cls):
        cls.setUpClassPyfakefs()
        # setup the fake filesystem using standard functions
        pathlib.Path("/test/file1.txt").touch()
        # you can also access the fake fs via fake_fs() if needed
        cls.fake_fs().create_file("/test/file2.txt", contents="test")

    def test1(self):
        self.assertTrue(os.path.exists("/test/file1.txt"))
        self.assertTrue(os.path.exists("/test/file2.txt"))
```
**Tests result** 
```
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/test'
```

**Your environment**

```bash
python -c "import platform; print(platform.platform())"
>>> Linux-6.5.0-17-generic-x86_64-with-glibc2.38

python -c "import sys; print('Python', sys.version)"
>>> Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]

python -c "from pyfakefs import __version__; print('pyfakefs', __version__)"
>>> pyfakefs 5.3.2

python -c "import pytest; print('pytest', pytest.__version__)"
>>> pytest 7.4.3
```

If necessary, I'm interested in helping here :grin:

**Comment by mrbean-bremen** [comment]
Thanks - certainly a documentation bug! `Path.touch()` indeed does not create the parent directories...
I'll probably replace it with:
```py
    @classmethod
    def setUpClass(cls):
        cls.setUpClassPyfakefs()
        # setup the fake filesystem using standard functions
        path = pathlib.Path("/test")
        path.mkdir()
        (path / "file1.txt").touch()
        # you can also access the fake fs via fake_fs() if needed
        cls.fake_fs().create_file("/test/file2.txt", contents="test")
```
What do you think?

**Comment by lsfischer** [comment]
sounds good to me!
