### ISSUE TITLE
Patched `os.symlink` mishandles directory descriptors

### ISSUE THREAD

**Issue by vector-of-bool** [pytest-dev/pyfakefs#968]
**Describe the bug**
The `os.symlink` function accepts a `dir_fd` argument to specify the destination of the created symlink. The fakefs `os.symlink` is behaves incorrectly and uses the `dir_fd` to rewrite the `src` argument:

```python
src = self._path_with_dir_fd(src, self.symlink, dir_fd)  # (wrong)
self.filesystem.create_symlink(dst, src, create_missing_dirs=False)
```

The `src` argument should be left verbatim as given. I am guessing that the code should have been written to resolve the `dst` argument instead:

```python
dst = self._path_with_dir_fd(dst, self.symlink, dir_fd)
self.filesystem.create_symlink(dst, src, create_missing_dirs=False)
```

The doc comment is written to reflect the incorrect behavior.

**How To Reproduce**
```python
def _test_symlink(base: Path):
    dir_fd = os.open(base, os.O_DIRECTORY)
    os.symlink("file.txt", "link.txt", dir_fd=dir_fd)
    assert os.readlink(base / "link.txt") == "file.txt"

def test_symlink_realfs(tmp_path: Path):
    _test_symlink(tmp_path)

def test_symlink_fakefs(fs):
    _test_symlink(Path("/tmp/"))
```

The `os.symlink` call above will succeed, but creates `link.txt` in the wrong location, leading to  `os.readlink` generating a `FileNotFoundError`.

**Your environment**
Please run the following in the environment where the problem happened and
paste the output.
```console
$ python -c "import platform; print(platform.platform())"
Linux-6.7.6-arch1-1-x86_64-with-glibc2.39
$ python -c "import sys; print('Python', sys.version)"
Python 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]
$ python -c "from pyfakefs import __version__; print('pyfakefs', __version__)"
pyfakefs 5.4.dev0
$ python -c "import pytest; print('pytest', pytest.__version__)"
pytest 7.2.0
```

**Comment by mrbean-bremen** [comment]
Thanks, that looks like an obvious bug, together with an incorrect or missing test.

**Comment by mrbean-bremen** [comment]
As usually: please test in main.
I will handle the other issue another day...

**Comment by vector-of-bool** [comment]
This appears to be fixed. Thanks again!
