### ISSUE TITLE
Missing mock of `os.dup`

### ISSUE THREAD

**Issue by vector-of-bool** [pytest-dev/pyfakefs#970]
**Describe the bug**
The `os.dup` function is not implemented by `pyfakefs`, and defers to the underlying `dup`. This can cause the pyfakefs file numbers to be given to the real `dup` syscall, leading to unexpected behavior.

**How To Reproduce**
```python
def read_with_dup(s: Path):
    s.write_text("heythere")
    fd1 = os.open(s, os.O_RDONLY)
    fd2 = os.dup(fd1)
    dat1 = os.read(fd1, 3)
    dat2 = os.read(fd2, 10)
    os.close(fd1)
    os.close(fd2)
    assert dat1 == b"hey"
    assert dat2 == b"there"

def test_realfs():
    read_with_dup(Path("file.txt"))

def test_fakefs(fs):
    read_with_dup(Path("file.txt"))
```

The fileno returned by the patched `os.open` will be given to the built-in `os.dup`, which may or may not generate an error depending on whether `fd1` is coincidentally equal to a real file descriptor. The call to `os.read(fd2)` will likely fail since the patched `os.read` will be given a fileno that wasn't created by `pyfakefs`.

**Your environment**
Please run the following in the environment where the problem happened and
paste the output.
```console
$ python -c "import platform; print(platform.platform())"
Linux-6.7.6-arch1-1-x86_64-with-glibc2.39
$ python -c "import sys; print('Python', sys.version)"
Python 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]
$ python -c "from pyfakefs import __version__; print('pyfakefs', __version__)"
pyfakefs 5.4.dev0
$ python -c "import pytest; print('pytest', pytest.__version__)"
pytest 7.2.0
```

---

This one may be trickier to solve since `os.dup` is also useful with non-filesystem file descriptors. i.e. it would be bad if `pyfakefs` broke `os.dup` for sockets and pipes. Distinguishing between a socket fileno and a fakefs fileno may require separating the domain of integers used by the fake os module.

**Comment by mrbean-bremen** [comment]
I remember having done something about that some time ago, but obviously didn't finish it...
Thanks for the daily issue 😀

**Comment by mrbean-bremen** [comment]
> This one may be trickier to solve since os.dup is also useful with non-filesystem file descriptors. i.e. it would be bad if pyfakefs broke os.dup for sockets and pipes. 

Hm, that would also be true for `open` and other calls. We currently only handle files (by faking them) and pipes (by pointing a fake descriptor to a real one). Both should also work for a fake `dup`.
I don't think that we support sockets at all. This never came up, probably because applications using sockets will usually not be used with pyfakefs, and I will probably just ignore that as long as it does not come in a real use case.

**Comment by mrbean-bremen** [comment]
@vector-of-bool - this was the last of your issues so far. I will wait with a release at least until you have retested with the current version.

**Comment by vector-of-bool** [comment]
Thanks! I'll test things out.
