### ISSUE TITLE
`os.getxattr` should raise `OSError(ENODATA)` for non-existent extended attributes

### ISSUE THREAD

**Issue by vector-of-bool** [pytest-dev/pyfakefs#971]
**Describe the bug**
The faked `os.getxattr` returns `None` if the extended attribute does not exist (and is documented as such). The standard `os.getxattr` either returns `bytes` or raises an `OSError` from the underlying syscall. The `getxattr` syscall fails with `ENODATA` if the attribute name is legal but is unset, and fails with `ENOTSUP` if the attribute name is illegal.

**How To Reproduce**
```python
def read_nonexistent_xattr(s: Path):
    s.write_text("file content")
    # Non-existent attribute:
    with pytest.raises(OSError) as exc:
        os.getxattr(s, "user.nonesuch_attribute")
    assert exc.value.errno == errno.ENODATA
    # Invalid attribute:
    with pytest.raises(OSError) as exc:
        os.getxattr(s, "invalid attribute name")
    assert exc.value.errno == errno.ENOTSUP

def test_realfs():
    read_nonexistent_xattr(Path("file.txt"))

def test_fakefs(fs):
    read_nonexistent_xattr(Path("file.txt"))
```

**Your environment**
Please run the following in the environment where the problem happened and
paste the output.
```console
$ python -c "import platform; print(platform.platform())"
Linux-6.7.6-arch1-1-x86_64-with-glibc2.39
$ python -c "import sys; print('Python', sys.version)"
Python 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]
$ python -c "from pyfakefs import __version__; print('pyfakefs', __version__)"
pyfakefs 5.4.dev0
$ python -c "import pytest; print('pytest', pytest.__version__)"
pytest 7.2.0
```

**Comment by mrbean-bremen** [comment]
Thanks! Keep in mind that real `xattr` support will not added to pyfakefs, but at least the behavior shall be as expected.
